title:  Cookbook Demo
titleSeparator: '-'
titleAddition: Des recettes pour pleins - demo site
description: Site de demonstration du theme hugo-enka-cookbook
images:
  - cover.png
ogLocale: fr
titleHome: Cookbook Demo
schemaType: Organization
schemaName: Cookbook Demo
schemaAuthor: encas-parka
schemaAuthorGitHub: https://github.com/encas-parka
schemaLocale: fr-FR
schemaLogo: logo.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: cover.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: ""
schemaLinkedIn: ""
schemaGitHub: ""
themeColor: '#fff'
quality: 85
bgColor: '#fff'
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: "320"
defaultImage: default-image.png
fillImage: 1280x720 Center
footer: Powered by <a href="https://www.netlify.com/">Netlify</a>, <a href="https://gohugo.io/">Hugo</a>, and <a href="https://gethyas.com/">Hyas</a>
copyRight: ""
alert: false
alertDismissable: true
alertText: ""
seo:
  - title:
    separator: " | "
    suffix: "Cookboo-Demo"
  - favicons:
    icon: "favicon.png"
    svgIcon: "favicon.svg"